name:                image-detection-haskell
version:             0.1.0.0
github:              "nathancgaar/image-detection-haskell"
license:             BSD-3-Clause
author:              "Nathan Gaar"
maintainer:          "nathancgaar@gmail.com"
copyright:           "2024 Nathan Gaar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/image-detection-haskell#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - dotenv >= 0.11.0.2
    - postgresql-simple == 0.7.0.0
    - scotty == 0.20.1
    - aeson == 2.1.2.1
    - text == 2.0.2
    - uuid >= 1.3.13
    - http-types == 0.12.4


executables:
  image-detection-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-detection-haskell
    - dotenv >=0.11.0.2
    - base >= 4.7 && < 5
    - postgresql-simple == 0.7.0.0
    - scotty == 0.20.1
    - aeson == 2.1.2.1 
    - text == 2.0.2
    - http-types == 0.12.4



tests:
  image-detection-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-detection-haskell
    - dotenv >=0.12.0.0

